node:
  image: joherma1/rpi-siarest
  ports:
    - "3000:3000"
  devices:
    - "/dev/ttyACM0:/dev/cu.usbmodem1411"
  links:
    - mongo
mongo:
  image: joherma1/rpi-mongo
  ports:
    - "27017:27017"